apiVersion: mysql.oci.upbound.io/v1alpha1
kind: MysqlConfiguration
metadata:
  labels:
    testing.upbound.io/example-name: mysqlconfiguration_label_1
  name: mysqlconfiguration1
spec:
  forProvider:
    # Refer to following terraform example for brief resource fields
    # https://registry.terraform.io/providers/oracle/oci/7.27.0/docs/resources/mysql_mysql_configuration
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: mysqlconfiguration1  #Optional_field
    shapeName: "MySQL.2"