apiVersion: cloudbridge.oci.upbound.io/v1alpha1
kind: Environment
metadata:
  annotations:
    meta.upbound.io/example-id: cloudbridge/v1alpha1/environment
  labels:
    testing.upbound.io/example-name: test_environment
  name: test-environment
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags: ${map(oci_identity_tag_namespace.tag-namespace1.name.oci_identity_tag.tag1.name,
      var.environment_defined_tags_value)}
    displayName: ${var.environment_display_name}
    freeformTags: ${var.environment_freeform_tags}
