apiVersion: database.oci.upbound.io/v1alpha1
kind: ApplicationVip
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/applicationvip
  labels:
    testing.upbound.io/example-name: test_application_vip
  name: test-application-vip
spec:
  forProvider:
    cloudVmClusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_cloud_vm_cluster
    dbNodeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_db_node
    hostnameLabel: ${var.application_vip_hostname_label}
    ipAddress: ${var.application_vip_ip_address}
    ipv6address: ${var.application_vip_ipv6address}
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_subnet
