apiVersion: dataintegration.oci.upbound.io/v1alpha1
kind: WorkspaceApplication
metadata:
  labels:
    testing.upbound.io/example-name: workspaceapplication_label_1
  name: workspaceapplication1
spec:
  forProvider:
    description: "Test Workspace Application"
    displayName: workspaceapplication1
    identifier: WORKSPACEAPPLICATION1
    modelType: "INTEGRATION_APPLICATION"
    name: workspaceapplication1
    workspaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: workspace_label_1
