apiVersion: artifacts.oci.upbound.io/v1alpha1
kind: ContainerConfiguration
metadata:
  labels:
    testing.upbound.io/example-name: containerconfiguration_label_1
  name: containerconfiguration1
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    isRepositoryCreatedOnFirstPush: False
