apiVersion: datasafe.oci.upbound.io/v1alpha1
kind: DatabaseSecurityConfig
metadata:
  annotations:
    meta.upbound.io/example-id: datasafe/v1alpha1/databasesecurityconfig
  labels:
    testing.upbound.io/example-name: test_database_security_config
  name: test-database-security-config
spec:
  forProvider:
    databaseSecurityConfigIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_database_security_config
    definedTags:
      Operations.CostCenter: "42"
    description: ${var.database_security_config_description}
    displayName: ${var.database_security_config_display_name}
    freeformTags:
      Department: Finance
    sqlFirewallConfig:
    - excludeJob: ${var.database_security_config_sql_firewall_config_exclude_job}
      status: ${var.database_security_config_sql_firewall_config_status}
      violationLogAutoPurge: ${var.database_security_config_sql_firewall_config_violation_log_auto_purge}
