apiVersion: datasafe.oci.upbound.io/v1alpha1
kind: DataSafeConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: datasafe/v1alpha1/datasafeconfiguration
  labels:
    testing.upbound.io/example-name: test_data_safe_configuration
  name: test-data-safe-configuration
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    isEnabled: ${var.data_safe_configuration_is_enabled}
