apiVersion: redis.oci.upbound.io/v1alpha1
kind: OciCacheConfigSetlistAssociatedOciCacheCluster
metadata:
  labels:
    testing.upbound.io/example-name: ocicacheconfigsetlistassociatedocicachecluster1_label_1
  name: ocicacheconfigsetlistassociatedocicachecluster1
spec:
  forProvider:
    # Refer to following terraform example for brief resource fields
    # https://registry.terraform.io/providers/oracle/oci/7.27.0/docs/resources/redis_oci_cache_config_setlist_associated_oci_cache_cluster
    ociCacheConfigSetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: ocicacheconfigset_label_1