apiVersion: redis.oci.upbound.io/v1alpha1
kind: OciCacheConfigSet
metadata:
  labels:
    testing.upbound.io/example-name: ocicacheconfigset_label_1
  name: ocicacheconfigset1
spec:
  forProvider:
    # Refer to following terraform example for brief resource fields
    # https://registry.terraform.io/providers/oracle/oci/7.27.0/docs/resources/redis_oci_cache_config_set
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    configurationDetails:
      - items:
          - configKey: timeout
            configValue: "0"   
    displayName: ocicacheconfigset1
    softwareVersion: "REDIS_7_0"