apiVersion: servicecatalog.oci.upbound.io/v1alpha1
kind: PrivateApplication
metadata:
  annotations:
    meta.upbound.io/example-id: servicecatalog/v1alpha1/privateapplication
  labels:
    testing.upbound.io/example-name: test_private_application
  name: test-private-application
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      foo-namespace.bar-key: value
    displayName: ${var.private_application_display_name}
    freeformTags:
      bar-key: value
    logoFileBase64Encoded: ${var.private_application_logo_file_base64encoded}
    longDescription: ${var.private_application_long_description}
    packageDetails:
    - packageType: ${var.private_application_package_details_package_type}
      version: ${var.private_application_package_details_version}
      zipFileBase64Encoded: ${var.private_application_package_details_zip_file_base64encoded}
    shortDescription: ${var.private_application_short_description}
