apiVersion: iot.oci.upbound.io/v1alpha1
kind: IotDomainGroupConfigureDataAccess
metadata:
  annotations:
    meta.upbound.io/example-id: iot/v1alpha1/iotdomaingroupconfiguredataaccess
  labels:
    testing.upbound.io/example-name: test_iot_domain_group_configure_data_access
  name: test-iot-domain-group-configure-data-access
spec:
  forProvider:
    dbAllowListedVcnIds: ${var.iot_domain_group_configure_data_access_db_allow_listed_vcn_ids}
    iotDomainGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_iot_domain_group
