apiVersion: stackmonitoring.oci.upbound.io/v1alpha1
kind: Config
metadata:
  annotations:
    meta.upbound.io/example-id: stackmonitoring/v1alpha1/config
  labels:
    testing.upbound.io/example-name: test_config_autopromote
  name: test-config-autopromote
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    configType: AUTO_PROMOTE
    isEnabled: true
    resourceType: HOST
