apiVersion: fusionapps.oci.upbound.io/v1alpha1
kind: FusionEnvironmentServiceAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: fusionapps/v1alpha1/fusionenvironmentserviceattachment
  labels:
    testing.upbound.io/example-name: test_fusion_environment_service_attachment
  name: test-fusion-environment-service-attachment
spec:
  forProvider:
    fusionEnvironmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_fusion_environment
    serviceInstanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_instance
    serviceInstanceType: ${var.fusion_environment_service_attachment_service_instance_type}
