apiVersion: datalabelingservice.oci.upbound.io/v1alpha1
kind: SafeSecurityPolicyDeploymentManagement
metadata:
  annotations:
    meta.upbound.io/example-id: datalabelingservice/v1alpha1/safesecuritypolicydeploymentmanagement
  labels:
    testing.upbound.io/example-name: test_security_policy_deployment_management
  name: test-security-policy-deployment-management
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      Operations.CostCenter: "42"
    description: ${var.security_policy_deployment_management_description}
    displayName: ${var.security_policy_deployment_management_display_name}
    freeformTags:
      Department: Finance
    securityPolicyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_security_policy
    targetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_target
    targetType: ${var.security_policy_deployment_management_target_type}
