apiVersion: datalabelingservice.oci.upbound.io/v1alpha1
kind: SafeSecurityPolicyDeployment
metadata:
  annotations:
    meta.upbound.io/example-id: datalabelingservice/v1alpha1/safesecuritypolicydeployment
  labels:
    testing.upbound.io/example-name: test_security_policy_deployment
  name: test-security-policy-deployment
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      Operations.CostCenter: "42"
    description: ${var.security_policy_deployment_description}
    displayName: ${var.security_policy_deployment_display_name}
    freeformTags:
      Department: Finance
    securityPolicyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_security_policy
    targetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_target
    targetType: ${var.security_policy_deployment_target_type}
