apiVersion: datalabelingservice.oci.upbound.io/v1alpha1
kind: SafeDataSafeConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: datalabelingservice/v1alpha1/safedatasafeconfiguration
  labels:
    testing.upbound.io/example-name: test_data_safe_configuration
  name: test-data-safe-configuration
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    isEnabled: ${var.data_safe_configuration_is_enabled}
