apiVersion: nosql.oci.upbound.io/v1alpha1
kind: Configuration
metadata:
  labels:
    testing.upbound.io/example-name: configuration_label_1
  name: configuration1
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    environment: HOSTED
